credentials:
  accessKeyID: YOUR_AWS_ACCESS_KEY_ID
  secretAccessKey: YOUR_AWS_SECRET_ACCESS_KEY
region: YOUR_AWS_REGION
clusterName: YOUR_CLUSTER_NAME
vpc:
  cidr: YOUR_VPC_CIDR
  subnet:
    public:
      cidr: YOUR_PUBLIC_SUBNET_CIDR
      az: YOUR_AZ
    private:
      cidr: YOUR_PRIVATE_SUBNET_CIDR
      az: YOUR_AZ
machine:
  instanceType: YOUR_INSTANCE_TYPE
  ami: YOUR_AMI_ID
  sshKeyName: YOUR_SSH_KEY_NAME
  securityGroups:
    - YOUR_SECURITY_GROUP_ID
networking:
  cni:
    type: YOUR_CNI_TYPE
  apiServer:
    loadBalancer:
      enabled: true
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"