# CRD do CAPD. Define como as máquinas viram containers Docker.
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: demo-cluster-workers
spec:
  template:
    spec: {} # Aqui poderiam ir configurações específicas do Docker Machine Template
              # mas como não tem nada, isso indica que usará as configurações padrão.
              # que são definidas no CAPD.
