# CRD do CAPI. Declara quantas máquinas e como elas são geridas.
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineSet
metadata:
  name: demo-cluster-workers
spec:
  clusterName: demo-cluster
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: demo-cluster
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: demo-cluster
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: demo-cluster-workers
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: demo-cluster-workers
